import http from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const rows = [
  { id: 1, title: 'Homepage title', status: 'Draft' },
  { id: 2, title: 'Pricing copy', status: 'Review' },
  { id: 3, title: 'About us heading', status: 'Approved' },
  { id: 4, title: 'Footer links', status: 'Exported' },
];

export function canRegenerateRow(row, { force, role }) {
  if (!row) return { allowed: false, reason: 'Row not found.' };
  if (row.status === 'Draft' || row.status === 'Review') return { allowed: true };

  if (row.status === 'Approved') {
    return force
      ? { allowed: true }
      : { allowed: false, reason: 'Approved rows require force=true to regenerate.' };
  }

  if (row.status === 'Exported') {
    return role === 'Admin'
      ? { allowed: true }
      : { allowed: false, reason: 'Exported rows can only be regenerated by Admin.' };
  }

  return { allowed: false, reason: `Unsupported status: ${row.status}` };
}

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

async function readJsonBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString('utf8');
  return raw ? JSON.parse(raw) : {};
}

async function handler(req, res) {
  const reqUrl = new URL(req.url, 'http://localhost');

  if (req.method === 'GET' && reqUrl.pathname === '/rows') {
    return sendJson(res, 200, { rows });
  }

  if (req.method === 'POST' && reqUrl.pathname === '/rows/regenerate') {
    let payload;
    try {
      payload = await readJsonBody(req);
    } catch {
      return sendJson(res, 400, { message: 'Invalid JSON payload.' });
    }

    const { rowIds, languages = [], force = false } = payload;
    const role = req.headers['x-role'] === 'admin' ? 'Admin' : 'User';

    if (!Array.isArray(rowIds) || rowIds.length === 0) {
      return sendJson(res, 400, { message: 'rowIds must be a non-empty array.' });
    }
    if (!Array.isArray(languages) || languages.length === 0) {
      return sendJson(res, 400, { message: 'languages must be a non-empty array.' });
    }

    const results = rowIds.map((rowId) => {
      const row = rows.find((item) => item.id === rowId);
      const decision = canRegenerateRow(row, { force, role });
      if (!decision.allowed) {
        return {
          rowId,
          status: row?.status ?? 'Unknown',
          regenerated: false,
          reason: decision.reason,
        };
      }
      return {
        rowId,
        status: row.status,
        regenerated: true,
        reason: `Regeneration queued for ${languages.join(', ')}.`,
      };
    });

    const regeneratedCount = results.filter((r) => r.regenerated).length;
    const rejectedCount = results.length - regeneratedCount;
    return sendJson(res, rejectedCount ? 207 : 200, {
      message: rejectedCount
        ? `Queued ${regeneratedCount}/${results.length} rows for regeneration.`
        : `Queued all ${results.length} row(s) for regeneration.`,
      force,
      role,
      results,
    });
  }

  if (req.method === 'GET' && reqUrl.pathname === '/') {
    const html = await readFile(path.join(__dirname, '../public/index.html'), 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(html);
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

export function createServer() {
  return http.createServer((req, res) => {
    handler(req, res).catch((err) => {
      sendJson(res, 500, { message: 'Internal server error', error: err.message });
    });
  });
}

if (process.argv[1] === __filename) {
  const port = Number(process.env.PORT || 3000);
  createServer().listen(port, () => {
    console.log(`Server running on http://localhost:${port}`);
  });
}
